Begin work with 3.0.0

diff --git a/rnaseq-driver b/rnaseq-driver
--- a/rnaseq-driver
+++ b/rnaseq-driver
@@ -1,85 +1,36 @@
-#!/bin/bash
+nf_script#!/bin/bash
 
-#!/bin/bash
-
-## NoteL The script may be initiated in either Illumina Runfolder OR the project work folder with same name as the project id specified in SampleSheet
-## A STANDARD RUN -- for which Demux is True -- should be initialted within the illumina runfolder. A project work folder is then created. The script will move to this folder and initialte the nextflow pipeline
-## ALT. In cases of re-running the complete pipeline without re-running the demux - start in the projectfolder. The script will then not re-run the initial steps of Sample sheet check etc.  Also, iff using fastq files from other sources.
-### ALT 1 regquires:
-#### 1. That the pipeline files are present in work folder, incliuding the project speciic nextflow config file, nextflow scripts and regular config.
-#### 2. Paramtera are imported from the the Sheet in ctg format AND the  project specific file.
-
-
-
-### 1/ Runfolder mode (runfolder_mode = true)
-# generate project folder
-# overwerites everything in project folder if exists (warns if exists)
-
-# check if initiated in a runfolder
-
-
-## 2. Project folder mode (runfolder_mode = false)
-### Require samplesheet must be same requirements as for 1. get project id from here and check pipeline parameter
-
-# 2.a . resume - false -
-# 2.a.1 skip demux  = false
-
-
-# 2.a.2 skip demcux = true
-
-
-# 2.b . resume - true -
-# check that all expected files are present - including nf log files
-# initiate nextflow with resume flag
-
-
-### RESUME MODE - THEN NO OTHER AHTN
 
 
 #######################################
 # ctg driver for  rnaseq pipeline
 #######################################
 
+## INPUT: CTG IEM Sample Sheet
+## INPUT: FASTQ files (default fastq parth is output from bcl2fastq analysis)
+
+
 ## !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! CHANGE WHEN DEPOLYT !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+
 # scriptsdir='/projects/fs1/shared/ctg-dev/pipelines/rnaseq/v1.0' # "/Users/david/scripts/ctg-rnaseq/workflow/" REPLACE WITH BASEDIR FROM SCRIPT EXECUTIoN
-# scripts_root='/Users/david/scripts' # "/Users/david/scripts/ctg-rnaseq/workflow/" REPLACE WITH BASEDIR FROM SCRIPT EXECUTIoN
-scripts_root="/projects/fs1/shared/ctg-dev/pipelines"
-# if DEVELOPMENT MODE, established pipelines are '/projects/fs1/shared/ctg-pieplines/pipelines/'
-# scriptsdir will be generated with this as base
-nf_pipe="rnaseq-main.nf"
+# scripts_root='/Users/david/scripts' #
 
-#  singularity_container='/projects/fs1/shared/ctg-dev/containers/uroscan/v1.4/uroscan.sif'
-
-# singularity_container='/projects/fs1/shared/ctg-containers/rnaseq/singularity-ctg-rnaseq-1.0.2.sif'
-singularity_container_rscript='/projects/fs1/shared/ctg-containers/rnaseq/singularity-ctg-rnaseq-1.0.2.sif'
-
-# singcmd="singularity exec --bind /projects/fs1/ ${singularity_container}"
-singcmd_rscript="singularity exec --bind /projects/fs1/ ${singularity_container_rscript}"
 
 ## Root directories (based on ourr set folder naming conventions on lsens)
-project_root='/projects/fs1/shared/ctg-projects/rnaseq'
-delivery_root='/projects/fs1/nas-sync/ctg-delivery/rnaseq'
-ctg_save_root='/projects/fs1/shared/ctg-qc/rnaseq'
-#project_root='/Users/david/tasks/nftest/projects' ## '/projects/fs1/shared/ctg-projects/uroscan'
-#delivery_root='/Users/david/tasks/nftest/delivery' ## '/projects/fs1/nas-sync/ctg-delivery/uroscan'
-#ctg_save_root='/Users/david/tasks/nftest/ctg-qc' # '/projects/fs1/shared/ctg-qc/uroscan'
+scripts_root="/projects/fs1/shared/ctg-dev/pipelines"
+project_root='/projects/fs1/shared/ctg-projects/ctg-rnaseq'
+delivery_root='/projects/fs1/shared/ctg-delivery/ctg-rnaseq' ## should be added pipelineProfile/ProjectID
+ctg_save_root='/projects/fs1/shared/ctg-qc/ctg-rnaseq' ## should be added pipelineProfile/ProjectID
+
+## Scripts
+rnaseq_script="rnaseq-main.sh"
+nf_script="rnaseq-main.nf"
 
 
-
-## Develiopment possibilities / known issues
-# - since the create samples sheet Rscripts are run in the driver, not in the nf workflow, strandness is not yet included in the ctg samplesheet
-# Chmods of generated files and fodlers !! should be full access by all within the lsens4 group. Add chmods to script? What about executables...
-
-## One nmore rscript to check if no deux samplesheet is supplied
 
 #######################################
 # Initiation - Prime the ctg rnaseq pipeline
 #######################################
-force_lane='0'
-force_index=false
-
-
-run_blcl2fastq=true
 fastq_custom=true ## set to false if no fastq_path is supplied (default no path)
 prime_run=false
 resume=false
@@ -92,7 +43,7 @@ usage() {
     echo "------------------- "
     echo " usage : "
     echo "------------------- "
-    echo " rnaseq-driver [ -s samplesheet ] [ -p prime_run_only ] [ -r resume ] [ -f fastq_path ] [ -l force_lane ] [ -i force_index ] [ -h help ] "  1>&2
+    echo " rnaseq-driver [ -s samplesheet ] [ -p prime_run_only ] [ -r resume ] [ -f fastq_path ] [ -h help ] "  1>&2
     echo ""
     echo "------------------- "
     echo " arguments : "
@@ -124,8 +75,6 @@ usage() {
     echo " prime_run_only:  -p : Set to 'true' if you do not start nextflow. A dry run that will generate project folder, config files etc but will not initiate nextflow."
     echo " fastq_path:      -f : Set to a full path where all fastq files are located. individual filenames should be specified in ctg sample sheet. This flag will set 'run_blcl2fastq' to 'false' and all flags related to demux to false "
     echo " resume           -r : Nextflow-specific. If to resume nextflow run. Can only be used when executing in Project work dir, NOT from Illumina runfolder"
-    echo " force_lane       -l : Set to 1 or 2 if to force demux to only run one lane. This if lane divider is used AND if lane is NOT specified in sample sheet. This parameter will override the Lane column in sample sheet"
-    echo " force_index:     -i : Set this flag if to force iem samplesheet Rscript to overwrite index id and sequence informations based on index well id. "
     echo " help             -h : print help message"
     echo "------------------- "
     echo ""
@@ -143,21 +92,20 @@ exit_abnormal() {
   exit 1
 }
 
+#######################################
 # Read and control input arguments
-while getopts ":s:l:f:r:p:ih" opt; do
+#######################################
+
+while getopts ":s:f:r:p:h" opt; do
     case $opt in
       s) samplesheet=$OPTARG
-	     ;;
-      l) force_lane=$OPTARG
-        ;;
+	          ;;
       f) fastq_path=$OPTARG
             ;;
       r) resume=true
-       	     ;;
+       	    ;;
       p) prime_run=true
             ;;
-      i) force_index=true
-          ;;
       h) exit_abnormal
         ;;
       \?) echo echo ""; echo "Error:";"Invalid option -$OPTARG" >&2
@@ -186,6 +134,7 @@ if [ ! -f $samplesheet ]; then
   exit_abnormal
 fi
 
+
 if [ -z $fastq_path ]; then
   fastq_custom=false
 fi
@@ -204,11 +153,19 @@ if [[ ${fastq_custom} == "true" ]]; then
 fi
 
 
+
 ################################################
-## Check Sample sheet variables
+## Read SampleSheet variables
 ################################################
 
-echo " Reading SampleSheet:"
+# check that samplesheet is a proper CTG IEM style sheet
+if [[ $(cat ${samplesheet} | grep "\[Header\]" | cut -f1 -d ",") != "[Header]" ]]
+  then
+    echo " ERROR: ${sheet} does not seem to be a valid SampleSheet - lacking first row [Header]."
+    exit 0
+fi
+
+echo " Reading SampleSheet parameters:"
 echo "  ... samplesheet: $samplesheet"
 
 
@@ -223,19 +180,16 @@ if [ -z "$projectid" ]; then
   echo " CTG Project id must be given as 'ProjectId' within the [Header] section of sample sheet"; echo""; echo ""
   exit_abnormal
 fi
-
 if [[ $projectid =~ ' ' ]]; then
   echo ""; echo ""; echo "Error: "
   echo " Warning: project id must not inlude white space ' '"; echo""; echo ""
   exit_abnormal
 fi
-
 if [[ $projectid =~ \\. ]]; then
   echo ""; echo ""; echo "Error: "
   echo " Warning: project id must not inlude a dot '.'"; echo""; echo ""
   exit_abnormal
 fi
-
 
 
 
@@ -434,8 +388,8 @@ if [[ $resume == "true" ]]; then
   echo " RESUME mode"
   echo " ... trying to resume nextflow"
   echo " ... Hail mary !!! "
-  nohup nextflow run $nf_pipe -c $nf_conf -profile ${pipelineProfile} --resume > log.nextflow.rnaseq &
-  echo " ... :  nextflow run $nf_pipe -c $nf_conf --resume"
+  nohup nextflow run $nf_script -c $nf_conf -profile ${pipelineProfile} --resume > log.nextflow.rnaseq &
+  echo " ... :  nextflow run $nf_script -c $nf_conf --resume"
 fi
 
 
@@ -737,7 +691,7 @@ if [[ $resume == "false" ]]; then
   # 4. Nextflow pipeline section
   ###################################################################
 
-  # nohup nextflow run $nf_pipe -c $nf_conf > log.nextflow.rnaseq &
+  # nohup nextflow run $nf_script -c $nf_conf > log.nextflow.rnaseq &
   cd ${projectdir}
   if [[ $prime_run == "false" ]]; then
 
@@ -771,7 +725,7 @@ if [[ $resume == "false" ]]; then
     echo "";echo ""
 
 
-    nohup nextflow run $nf_pipe -c $nf_conf -profile ${pipelineProfile} > log.nextflow.progress &
+    nohup nextflow run $nf_script -c $nf_conf -profile ${pipelineProfile} > log.nextflow.progress &
 
     echo "  Running :   nextflow run $nf_pipe -c $nf_conf -profile ${pipelineProfile}"
     echo "  Singularity container:  ${singularity_container}"
